"use client";
import { FormEvent, useEffect, useState } from "react";

type Proposal = { quote:{destination:string;travelers:number;subtotal:number;taxes:number;total:number;status:string;valid_until:string;notes:string;client_name:string;agency_name:string;accepted_at:string|null;accepted_name:string|null};items:Array<{category:string;description:string;quantity:number;unit_price:number;total:number}> };
const currency=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});

export function ProposalClient({token}:{token:string}){
  const [data,setData]=useState<Proposal|null>(null),[error,setError]=useState(""),[accepted,setAccepted]=useState(false),[saving,setSaving]=useState(false);
  useEffect(()=>{void fetch(`/api/proposal/${token}`,{cache:"no-store"}).then(async response=>{const payload=await response.json() as Proposal & {error?:string};if(!response.ok)throw new Error(payload.error);setData(payload);}).catch(cause=>setError(cause instanceof Error?cause.message:"No se pudo abrir la cotización."));},[token]);
  async function accept(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const name=String(new FormData(event.currentTarget).get("name")||"");const response=await fetch(`/api/proposal/${token}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const payload=await response.json() as {error?:string};setSaving(false);if(!response.ok){setError(payload.error||"No se pudo aceptar la propuesta.");return;}setAccepted(true);}
  if(error&&!data)return <main className="proposal-page"><section className="proposal-card"><h1>No pudimos abrir esta cotización</h1><p>{error}</p></section></main>;
  if(!data)return <main className="proposal-page"><section className="proposal-card"><p>Cargando propuesta…</p></section></main>;
  const {quote,items}=data,isAccepted=accepted||quote.status==="Aceptada";
  return <main className="proposal-page"><section className="proposal-card"><header><div className="brand-mark">R</div><div><strong>{quote.agency_name}</strong><small>Propuesta de viaje</small></div><button className="print-proposal" onClick={()=>window.print()}>Imprimir / PDF</button><span className={`status ${isAccepted?"confirmado":""}`}>{isAccepted?"Aceptada":quote.status}</span></header><div className="proposal-hero"><p>PREPARADO PARA {quote.client_name.toUpperCase()}</p><h1>{quote.destination}</h1><span>{quote.travelers} viajeros · válida hasta {quote.valid_until}</span></div><div className="proposal-items">{items.map((item,index)=><article key={index}><span>{item.category}</span><div><strong>{item.description}</strong><small>{item.quantity} × {currency.format(item.unit_price)}</small></div><b>{currency.format(item.total)}</b></article>)}</div><div className="proposal-summary"><p><span>Subtotal</span><b>{currency.format(quote.subtotal)}</b></p><p><span>Impuestos</span><b>{currency.format(quote.taxes)}</b></p><p className="total"><span>Total</span><b>{currency.format(quote.total)}</b></p></div>{quote.notes&&<div className="proposal-notes"><strong>Notas de la propuesta</strong><p>{quote.notes}</p></div>}{isAccepted?<div className="proposal-accepted"><strong>✓ Propuesta aceptada</strong><p>Gracias. Tu asesor continuará con la confirmación del viaje.</p></div>:<form className="proposal-accept" onSubmit={accept}><label>Nombre de quien acepta<input name="name" required minLength={2} placeholder="Nombre completo"/></label>{error&&<p role="alert">{error}</p>}<button disabled={saving}>{saving?"Registrando…":"Aceptar propuesta"}</button><small>Al aceptar confirmas que revisaste los servicios y totales mostrados.</small></form>}</section></main>;
}
