"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Agency = { id:number; name:string; status:string; plan:string; phone:string; trial_ends_at:string|null; created_at:string; updated_at:string|null; owner_email:string|null; owner_name:string|null; client_count:number; member_count:number; trip_count:number; quote_count:number; last_access:string|null; stripe_customer_id:string|null; stripe_subscription_id:string|null; monthly_price:number; billing_status:string; next_billing_at:string|null };
type Note = { id:number; agency_id:number; author_email:string; note:string; created_at:string };
type Activity = { id:number; agency_id:number; actor_email:string; action:string; entity_type:string; created_at:string };
type Payload = { agencies?:Agency[]; notes?:Note[]; activity?:Activity[]; error?:string };
const statusLabels:Record<string,string>={trial:"En prueba",active:"Activa",expired:"Vencida",suspended:"Suspendida"};
const planLabels:Record<string,string>={trial:"Prueba",starter:"Starter",professional:"Professional",enterprise:"Enterprise"};
const billingLabels:Record<string,string>={not_configured:"Sin configurar",trial:"En prueba",current:"Al corriente",past_due:"Pago atrasado",paused:"Pausado",cancelled:"Cancelado"};
const actionLabels:Record<string,string>={status:"Cambió el acceso",extend:"Extendió la prueba",note:"Agregó una nota",plan:"Cambió el plan",billing:"Actualizó el cobro"};
const date=(value:string|null,withTime=false)=>value?new Intl.DateTimeFormat("es-US",withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}).format(new Date(value)):"—";

export function SuperadminDashboard(){
  const [data,setData]=useState<Agency[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [activity,setActivity]=useState<Activity[]>([]);
  const [selectedId,setSelectedId]=useState<number|null>(null); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all");
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const [note,setNote]=useState("");
  const load=useCallback(async()=>{try{setError("");const r=await fetch("/admin/control/api",{credentials:"include",cache:"no-store"});const d=await r.json() as Payload;if(!r.ok)throw new Error(d.error);setData(d.agencies||[]);setNotes(d.notes||[]);setActivity(d.activity||[]);setSelectedId(current=>current??d.agencies?.[0]?.id??null);}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar.");}},[]);
  useEffect(()=>{
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  const selected=data.find(a=>a.id===selectedId)||null;
  const filtered=useMemo(()=>data.filter(a=>(filter==="all"||a.status===filter)&&`${a.name} ${a.owner_name||""} ${a.owner_email||""}`.toLowerCase().includes(search.toLowerCase())),[data,filter,search]);
  const agencyNotes=notes.filter(n=>n.agency_id===selectedId); const agencyActivity=activity.filter(a=>a.agency_id===selectedId);
  const monthlyRevenue=data.filter(a=>a.billing_status==="current").reduce((sum,a)=>sum+Number(a.monthly_price||0),0);
  async function act(action:string,agencyId:number,extra:Record<string,unknown>={},message="Actualización guardada."){setBusy(true);setError("");setNotice("");try{const r=await fetch("/admin/control/api",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({action,agencyId,...extra})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"No se pudo actualizar.");await load();setNotice(message);}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar.");}finally{setBusy(false);}}
  async function saveNote(e:FormEvent){e.preventDefault();if(!selected||!note.trim())return;await act("note",selected.id,{note},"Nota comercial agregada.");setNote("");}
  async function savePlan(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);await act("plan",selected.id,{plan:fd.get("plan")},"Plan actualizado.");}
  async function saveBilling(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const fd=new FormData(e.currentTarget);await act("billing",selected.id,{monthlyPrice:Number(fd.get("monthlyPrice")),billingStatus:fd.get("billingStatus"),nextBillingAt:fd.get("nextBillingAt")||null},"Configuración de cobro guardada.");}
  return <main className="superadmin-page">
    <header className="seller-header"><div><p className="landing-kicker"><span/>CONTROL DEL VENDEDOR</p><h1>Centro de administración</h1><p>Controla agencias, pruebas, planes, cobros y seguimiento comercial desde un solo lugar.</p></div><a href="/">Ver sitio público ↗</a></header>
    {error&&<div className="error-banner"><span>{error}</span><button onClick={()=>setError("")} aria-label="Cerrar">×</button></div>}{notice&&<div className="notice-banner"><span>{notice}</span><button onClick={()=>setNotice("")} aria-label="Cerrar">×</button></div>}
    <section className="superadmin-metrics seller-metrics"><article><small>AGENCIAS</small><strong>{data.length}</strong><span>{data.filter(a=>a.status==="trial").length} en prueba</span></article><article><small>CLIENTES ACTIVOS</small><strong>{data.filter(a=>a.status==="active").length}</strong><span>{data.filter(a=>a.status==="suspended").length} suspendidas</span></article><article><small>INGRESO MENSUAL</small><strong>{monthlyRevenue.toLocaleString("en-US",{style:"currency",currency:"USD"})}</strong><span>Cobros marcados al corriente</span></article><article><small>USO TOTAL</small><strong>{data.reduce((s,a)=>s+a.client_count,0)}</strong><span>clientes registrados</span></article></section>
    <section className="seller-toolbar"><div className="seller-search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar agencia, contacto o correo" aria-label="Buscar agencias"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrar por estado"><option value="all">Todos los estados</option><option value="trial">En prueba</option><option value="active">Activas</option><option value="expired">Vencidas</option><option value="suspended">Suspendidas</option></select><button onClick={()=>void load()} disabled={busy}>Actualizar</button></section>
    <div className="seller-layout">
      <section className="agency-table seller-list"><div className="agency-row agency-head"><span>Agencia</span><span>Contacto</span><span>Estado</span><span>Uso</span><span>Administrar</span></div>{filtered.length===0&&<div className="seller-empty">No hay agencias que coincidan con la búsqueda.</div>}{filtered.map(a=><div className={`agency-row ${selectedId===a.id?"selected":""}`} key={a.id}><span><strong>{a.name}</strong><small>Registrada {date(a.created_at)}</small></span><span>{a.owner_name||"Sin nombre"}<small>{a.owner_email||"Sin correo"}<br/>{a.phone||"Sin teléfono"}</small></span><span><b className={`status-pill ${a.status}`}>{statusLabels[a.status]||a.status}</b><small>{planLabels[a.plan]||a.plan}</small></span><span>{a.client_count} clientes<small>{a.member_count} usuarios · {a.trip_count} viajes</small></span><span className="admin-actions"><button onClick={()=>setSelectedId(a.id)}>Ver y administrar</button></span></div>)}</section>
      {selected&&<section className="agency-detail">
        <div className="detail-heading"><div><p>AGENCIA SELECCIONADA</p><h2>{selected.name}</h2><span>ID #{selected.id} · Alta {date(selected.created_at)}</span></div><b className={`status-pill ${selected.status}`}>{statusLabels[selected.status]}</b></div>
        <nav className="detail-jump" aria-label="Secciones de la agencia"><a href="#resumen">Resumen</a><a href="#acceso">Acceso</a><a href="#plan">Plan y cobro</a><a href="#notas">Notas</a><a href="#historial">Historial</a></nav>
        <article id="resumen" className="detail-card"><div className="detail-card-title"><div><h3>Resumen de la cuenta</h3><p>Datos del propietario y actividad actual de la agencia.</p></div></div><dl className="detail-data"><div><dt>Propietario</dt><dd>{selected.owner_name||"No registrado"}</dd></div><div><dt>Correo</dt><dd>{selected.owner_email||"No registrado"}</dd></div><div><dt>Teléfono</dt><dd>{selected.phone||"No registrado"}</dd></div><div><dt>Último acceso</dt><dd>{date(selected.last_access,true)}</dd></div></dl><div className="usage-grid"><span><b>{selected.client_count}</b>Clientes</span><span><b>{selected.member_count}</b>Usuarios</span><span><b>{selected.trip_count}</b>Viajes</span><span><b>{selected.quote_count}</b>Cotizaciones</span></div></article>
        <article id="acceso" className="detail-card"><div className="detail-card-title"><div><h3>Acceso y período de prueba</h3><p>Activa, suspende o extiende el acceso al CRM.</p></div></div><dl className="detail-data"><div><dt>Estado actual</dt><dd>{statusLabels[selected.status]}</dd></div><div><dt>Fin de prueba</dt><dd>{date(selected.trial_ends_at)}</dd></div></dl><div className="detail-actions"><button onClick={()=>act("extend",selected.id,{days:14},"Prueba extendida 14 días.")} disabled={busy}>+14 días</button><button onClick={()=>act("extend",selected.id,{days:30},"Prueba extendida 30 días.")} disabled={busy}>+30 días</button><button className={selected.status==="suspended"?"success":"danger"} onClick={()=>act("status",selected.id,{status:selected.status==="suspended"?"active":"suspended"},selected.status==="suspended"?"Agencia activada.":"Agencia suspendida.")} disabled={busy}>{selected.status==="suspended"?"Activar agencia":"Suspender agencia"}</button></div></article>
        <article id="plan" className="detail-card"><div className="detail-card-title"><div><h3>Plan y cobro</h3><p>Preparado para administrar la suscripción manualmente mientras Stripe permanece desconectado.</p></div><span className="integration-badge">Stripe no conectado</span></div><form className="admin-form" onSubmit={savePlan}><label>Plan asignado<select name="plan" defaultValue={selected.plan} key={`plan-${selected.id}-${selected.plan}`}><option value="trial">Prueba</option><option value="starter">Starter</option><option value="professional">Professional</option><option value="enterprise">Enterprise</option></select><small>Define las condiciones comerciales asignadas a esta agencia.</small></label><button disabled={busy}>Guardar plan</button></form><form className="admin-form billing-form" onSubmit={saveBilling}><label>Precio mensual (USD)<input name="monthlyPrice" type="number" min="0" step="0.01" defaultValue={selected.monthly_price} key={`price-${selected.id}-${selected.monthly_price}`}/><small>Úsalo para llevar control aunque todavía no haya cobro automático.</small></label><label>Estado del cobro<select name="billingStatus" defaultValue={selected.billing_status} key={`billing-${selected.id}-${selected.billing_status}`}>{Object.entries(billingLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Próximo cobro<input name="nextBillingAt" type="date" defaultValue={selected.next_billing_at?.slice(0,10)||""} key={`next-${selected.id}-${selected.next_billing_at}`}/></label><button disabled={busy}>Guardar cobro</button></form><div className="stripe-status"><span>Cliente Stripe: {selected.stripe_customer_id||"No creado"}</span><span>Suscripción Stripe: {selected.stripe_subscription_id||"No creada"}</span></div></article>
        <article id="notas" className="detail-card"><div className="detail-card-title"><div><h3>Notas comerciales</h3><p>Guarda llamadas, acuerdos, seguimiento y cualquier detalle importante.</p></div></div><form className="note-form" onSubmit={saveNote}><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="Ejemplo: Llamé al propietario; desea comenzar el plan Professional el próximo lunes."/><div><small>{note.length}/2000</small><button disabled={busy||!note.trim()}>Agregar nota</button></div></form><div className="timeline">{agencyNotes.length===0&&<p className="seller-empty">Todavía no hay notas comerciales.</p>}{agencyNotes.map(n=><div className="timeline-item" key={n.id}><span>✎</span><div><p>{n.note}</p><small>{n.author_email} · {date(n.created_at,true)}</small></div></div>)}</div></article>
        <article id="historial" className="detail-card"><div className="detail-card-title"><div><h3>Historial administrativo</h3><p>Registro de cambios realizados desde el panel del vendedor.</p></div></div><div className="timeline">{agencyActivity.length===0&&<p className="seller-empty">Todavía no hay acciones registradas.</p>}{agencyActivity.map(item=>{const parts=item.action.split(":");return <div className="timeline-item" key={item.id}><span>✓</span><div><p>{actionLabels[parts[1]]||item.action}{parts[2]?`: ${parts[2]}`:""}</p><small>{item.actor_email} · {date(item.created_at,true)}</small></div></div>})}</div></article>
      </section>}
    </div>
  </main>;
}
