"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
type Client={id:number;name:string;email:string;phone:string;destination:string;status:string};
type Trip={id:number;client_id:number;client_name:string;destination:string;start_date:string;end_date:string;total:number;status:string};
type Payment={id:number;trip_id:number;client_name:string;destination:string;amount:number;due_date:string;paid_at:string|null;method:string;note:string};
type Task={id:number;client_id:number|null;client_name:string|null;title:string;due_date:string;priority:string;completed:number};
type Data={clients:Client[];trips:Trip[];payments:Payment[];tasks:Task[]}; type Modal="client"|"payment"|"task"|null;
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const shortDate=(v:string)=>new Intl.DateTimeFormat("es-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${v}T12:00:00Z`));

export function CrmDashboard(){
 const[data,setData]=useState<Data>({clients:[],trips:[],payments:[],tasks:[]});const[loading,setLoading]=useState(true);const[section,setSection]=useState("Inicio");const[modal,setModal]=useState<Modal>(null);const[search,setSearch]=useState("");const[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/data",{cache:"no-store"});setData(await r.json());setLoading(false)},[]);useEffect(()=>{load()},[load]);
 const pending=data.payments.filter(p=>!p.paid_at),dueTotal=pending.reduce((s,p)=>s+Number(p.amount),0),collected=data.payments.filter(p=>p.paid_at).reduce((s,p)=>s+Number(p.amount),0),openTasks=data.tasks.filter(t=>!t.completed);
 const filtered=useMemo(()=>data.clients.filter(c=>`${c.name} ${c.email} ${c.phone} ${c.destination}`.toLowerCase().includes(search.toLowerCase())),[data.clients,search]);
 async function submit(action:string,values:Record<string,FormDataEntryValue>){setSaving(true);await post(action,values);await load();setSaving(false);setModal(null)}
 async function post(action:string,values:Record<string,unknown>){await fetch("/api/data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...values})})}
 async function quick(action:string,values:Record<string,unknown>){await post(action,values);await load()}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">V</span><div><strong>Vía Clara</strong><small>Travel CRM</small></div></div><nav>{["Inicio","Clientes","Viajes","Pagos","Tareas","Reportes"].map((item,i)=><button key={item} className={section===item?"active":""} onClick={()=>setSection(item)}><span>{["⌂","◎","✦","$","✓","↗"][i]}</span>{item}</button>)}</nav><div className="sidebar-foot"><div className="avatar">ND</div><div><strong>Noel Díaz</strong><small>Administrador</small></div><span>•••</span></div></aside>
 <main><header className="topbar"><div><p className="eyebrow">VIERNES, 14 DE AGOSTO</p><h1>{section}</h1></div><div className="top-actions"><label className="search">⌕<input aria-label="Buscar" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente..."/></label><button className="notification" aria-label="Notificaciones">◦</button><button className="primary" onClick={()=>setModal("client")}>＋ Nuevo cliente</button></div></header>
 {loading?<div className="loading">Organizando tu agencia…</div>:section==="Inicio"?<><section className="hero-row"><div><p className="eyebrow coral">RESUMEN DE HOY</p><h2>Buenos días, Noel.</h2><p>Tienes <strong>{openTasks.length} pendientes</strong> y <strong>{pending.length} cobros</strong> que requieren atención.</p></div><button className="soft-button" onClick={()=>setModal("task")}>＋ Agregar tarea</button></section>
 <section className="metrics"><Metric label="Por cobrar" value={money.format(dueTotal)} note={`${pending.length} pagos pendientes`} tone="coral"/><Metric label="Cobrado" value={money.format(collected)} note="Pagos registrados" tone="green"/><Metric label="Viajes activos" value={String(data.trips.length)} note={`${data.trips.filter(t=>t.status==="Confirmado").length} confirmados`} tone="blue"/><Metric label="Clientes" value={String(data.clients.length)} note="Base de contactos" tone="sand"/></section>
 <section className="grid-two"><div className="panel"><PanelTitle title="Próximos cobros" action="Ver todos" onClick={()=>setSection("Pagos")}/><div className="rows">{pending.slice(0,4).map(p=><div className="payment-row" key={p.id}><div className="date-chip"><b>{shortDate(p.due_date).split(" ")[1]}</b><span>{shortDate(p.due_date).split(" ")[0]}</span></div><div className="grow"><strong>{p.client_name}</strong><small>{p.destination} · {p.note}</small></div><div className="amount"><strong>{money.format(p.amount)}</strong><button onClick={()=>quick("markPaid",{id:p.id,method:"Registrado"})}>Registrar</button></div></div>)}</div></div>
 <div className="panel"><PanelTitle title="Tareas pendientes" action="Nueva tarea" onClick={()=>setModal("task")}/><div className="rows">{openTasks.slice(0,4).map(t=><label className="task-row" key={t.id}><input type="checkbox" onChange={()=>quick("toggleTask",{id:t.id,completed:true})}/><span className={t.priority==="Alta"?"check high":"check"}/><div className="grow"><strong>{t.title}</strong><small>{t.client_name||"Tarea interna"}</small></div><time>{shortDate(t.due_date)}</time></label>)}</div></div></section>
 <section className="panel upcoming"><PanelTitle title="Próximos viajes" action="Ver calendario" onClick={()=>setSection("Viajes")}/><div className="trip-grid">{data.trips.map(t=><div className="trip-card" key={t.id}><div className="trip-icon">{t.destination[0]}</div><div><span className={`status ${t.status.toLowerCase()}`}>{t.status}</span><h3>{t.destination}</h3><p>{t.client_name}</p><small>{shortDate(t.start_date)} — {shortDate(t.end_date)}</small></div><strong>{money.format(t.total)}</strong></div>)}</div></section></>:
 section==="Clientes"?<ListPage title="Clientes" description="Toda la relación con tus viajeros en un solo lugar." action="Nuevo cliente" onAction={()=>setModal("client")}><div className="table-list">{filtered.map(c=><div className="client-line" key={c.id}><div className="client-avatar">{c.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div className="grow"><strong>{c.name}</strong><small>{c.email} · {c.phone}</small></div><span>{c.destination}</span><span className="status confirmado">{c.status}</span></div>)}</div></ListPage>:
 section==="Viajes"?<ListPage title="Viajes" description="Reservas, fechas y saldos de cada experiencia."><div className="table-list">{data.trips.map(t=><div className="client-line" key={t.id}><div className="trip-icon small">{t.destination[0]}</div><div className="grow"><strong>{t.destination}</strong><small>{t.client_name} · {shortDate(t.start_date)} — {shortDate(t.end_date)}</small></div><strong>{money.format(t.total)}</strong><span className="status confirmado">{t.status}</span></div>)}</div></ListPage>:
 section==="Pagos"?<ListPage title="Pagos" description={`${money.format(dueTotal)} pendientes por cobrar.`} action="Agregar pago" onAction={()=>setModal("payment")}><div className="table-list">{data.payments.map(p=><div className="client-line" key={p.id}><div className={`pay-dot ${p.paid_at?"paid":""}`}>$</div><div className="grow"><strong>{p.client_name}</strong><small>{p.destination} · {p.note} · vence {shortDate(p.due_date)}</small></div><strong>{money.format(p.amount)}</strong>{p.paid_at?<span className="status confirmado">Pagado</span>:<button className="mini-button" onClick={()=>quick("markPaid",{id:p.id,method:"Registrado"})}>Registrar pago</button>}</div>)}</div></ListPage>:
 section==="Tareas"?<ListPage title="Tareas" description="Seguimientos y recordatorios del equipo." action="Nueva tarea" onAction={()=>setModal("task")}><div className="table-list">{data.tasks.map(t=><label className={`client-line ${t.completed?"done":""}`} key={t.id}><input type="checkbox" checked={!!t.completed} onChange={()=>quick("toggleTask",{id:t.id,completed:!t.completed})}/><div className="grow"><strong>{t.title}</strong><small>{t.client_name||"Tarea interna"}</small></div><span>{shortDate(t.due_date)}</span><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span></label>)}</div></ListPage>:
 <ListPage title="Reportes" description="Una vista clara de la salud de tu agencia."><section className="metrics reports"><Metric label="Ventas activas" value={money.format(data.trips.reduce((s,t)=>s+Number(t.total),0))} note="Valor de viajes" tone="blue"/><Metric label="Cobranza" value={money.format(collected)} note="Ingresos registrados" tone="green"/><Metric label="Cuentas por cobrar" value={money.format(dueTotal)} note="Saldo pendiente" tone="coral"/></section></ListPage>}</main>
 {modal&&<ModalForm type={modal} clients={data.clients} trips={data.trips} saving={saving} close={()=>setModal(null)} submit={submit}/>}</div>
}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <article className="metric"><span className={`metric-icon ${tone}`}>{tone==="coral"?"$":tone==="green"?"✓":tone==="blue"?"✦":"◎"}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></article>}
function PanelTitle({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="panel-title"><h3>{title}</h3><button onClick={onClick}>{action} →</button></div>}
function ListPage({title,description,action,onAction,children}:{title:string;description:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <section className="list-page"><div className="list-head"><div><h2>{title}</h2><p>{description}</p></div>{action&&<button className="primary" onClick={onAction}>＋ {action}</button>}</div><div className="panel">{children}</div></section>}
function ModalForm({type,clients,trips,saving,close,submit}:{type:Exclude<Modal,null>;clients:Client[];trips:Trip[];saving:boolean;close:()=>void;submit:(a:string,v:Record<string,FormDataEntryValue>)=>void}){const send=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();submit(type,Object.fromEntries(new FormData(e.currentTarget)))};return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><form className="modal" onSubmit={send}><div className="modal-head"><div><p className="eyebrow coral">NUEVO REGISTRO</p><h2>{type==="client"?"Agregar cliente":type==="payment"?"Agregar pago":"Agregar tarea"}</h2></div><button type="button" onClick={close}>×</button></div>{type==="client"&&<><Field label="Nombre completo" name="name" required/><div className="form-grid"><Field label="Teléfono" name="phone"/><Field label="Email" name="email" type="email"/></div><Field label="Destino de interés" name="destination"/></>}{type==="payment"&&<><label>Viaje<select name="tripId" required>{trips.map(t=><option key={t.id} value={t.id}>{t.client_name} — {t.destination}</option>)}</select></label><div className="form-grid"><Field label="Monto (USD)" name="amount" type="number" required/><Field label="Vencimiento" name="dueDate" type="date" required/></div><Field label="Concepto" name="note" placeholder="Anticipo, cuota, saldo…"/></>}{type==="task"&&<><Field label="Tarea" name="title" required/><label>Cliente<select name="clientId"><option value="">Tarea interna</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><Field label="Fecha" name="dueDate" type="date" required/><label>Prioridad<select name="priority"><option>Normal</option><option>Alta</option><option>Baja</option></select></label></div></>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando…":"Guardar"}</button></div></form></div>}
function Field({label,name,type="text",required,placeholder}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string}){return <label>{label}<input name={name} type={type} required={required} placeholder={placeholder}/></label>}
